# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Ejemplos Java
logo: images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Information about where the book exists on the web
repository:
  url: https://github.com/tigarto/java_misiontic_codes  # Online location of your book
  branch: master  

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  colab_url: https://colab.research.google.com
